from distutils.core import setup

setup(name='python-edgar',
      version='1.0',
      description='A downloader of the SEC EDGAR index since 1993 (company name, form type, EDGAR form url)',
      author='Edouard Swiac',
      author_email='edouard.swiac@gmail.com',
      url='https://github.com/edouardswiac/python-edgar',
      packages=['edgar'],
      license="MIT License",
      classifiers = [
          "Development Status :: 4 - Beta",
          "License :: OSI Approved :: MIT License",
          "Intended Audience :: Developers",
          "Intended Audience :: Information Technology",
          "Intended Audience :: Financial and Insurance Industry",
          "Operating System :: OS Independent",
          "Programming Language :: Python",
          "Programming Language :: Python :: 2",
          "Programming Language :: Python :: 2.6",
          "Programming Language :: Python :: 2.7",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3.2",
          "Programming Language :: Python :: 3.3",
          "Programming Language :: Python :: Implementation :: CPython",
          "Programming Language :: Python :: Implementation :: PyPy",
          "Topic :: Office/Business :: Financial",
          "Topic :: Office/Business :: Financial :: Investment"
      ],
     )